# Genes Location Retrieval
### Laurence Nickel (i6257119)

Libraries used: 
* biomaRt (version: '2.54.1')
* data.table (version: '1.14.8') 

## Introduction

Within this notebook, the location data of the genes present within the gene expression data files will be retrieved. The human reference genome 'hg19' (human genome version h19), which is also the reference genome used by the 'IlluminaHumanMethylation450kanno.ilmn12.hg19' annotation package, is used to retrieve the locations of the genes as the reference genome is generally considered to be a good estimate for the location data of the genes in the majority of individuals of that species.

For reproducibility purposes, the human reference genome 'hg19' has been retrieved on the date: 17-May-23 (14:19).

### Importing libraries

Before we start the retrieval of the locations of the genes, we should first import some libraries that will be used throughout this notebook. These libraries can be installed through 'BiocManager'.

In [1]:
# Checking whether the package 'BiocManager' has already been installed and installing it if it has not been installed yet.
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")


cat("Starting the installing of the libraries...")


# Using 'BiocManager' to install the following libraries (which are also mentioned in the introduction of this notebook).
BiocManager::install('biomaRt')

# Using the R command 'install.packages()' to install the remaining necessary libraries.
install.packages("data.table")


cat("Finishing the installing of the libraries.")

Bioconductor version '3.16' is out-of-date; the current release version '3.17'
  is available with R version '4.3'; see https://bioconductor.org/install



Starting the installing of the libraries...

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.r-project.org

Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.3 (2023-03-15 ucrt)

Warning message:
"package(s) not installed when version(s) same as or greater than current; use
  `force = TRUE` to re-install: 'biomaRt'"
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.2.3/library
  packages:
    class, KernSmooth, lattice, MASS, Matrix, nnet, survival

Old packages: 'cachem', 'DelayedArray', 'dplyr', 'evaluate', 'fs', 'httpuv',
  'httr', 'httr2', 'later', 'profvis', 'rlang', 'sass', 'testthat', 'tzdb',
  'vctrs', 'viridisLite', 'vroom', 'waldo', 'xfun', 'xml2'

Installing package into 'C:/Users/laure/AppData/Local/R/win-library/4.2'
(as 'lib' is unspecified)



package 'data.table' successfully unpacked and MD5 sums checked


Warning message:
"cannot remove prior installation of package 'data.table'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\laure\AppData\Local\R\win-library\4.2\00LOCK\data.table\libs\x64\data_table.dll to C:\Users\laure\AppData\Local\R\win-library\4.2\data.table\libs\x64\data_table.dll: Permission denied"
Warning message:
"restored 'data.table'"



The downloaded binary packages are in
	C:\Users\laure\AppData\Local\Temp\RtmpEN9DXP\downloaded_packages
Finishing the installing of the libraries.

Now that all the libraries have been installed we can load them into this notebook by using the command 'libraries()'. To verify that these libraries have been loaded into this notebook, we can use the command 'packageVersion()' which will display the version of the package currently installed.

In [2]:
# Loading the following libraries (which are also mentioned in the introduction of this notebook) into this notebook. 
library(biomaRt)
library(data.table)


# Retrieving the version of the packages to verify they have been correctly loaded into this notebook.
cat("The library 'biomaRt' has been loaded into the notebook with its version being:")
packageVersion("biomaRt")

cat("The library 'data.table' has been loaded into the notebook with its version being:")
packageVersion("data.table")

The library 'biomaRt' has been loaded into the notebook with its version being:

[1] '2.54.1'

The library 'data.table' has been loaded into the notebook with its version being:

[1] '1.14.8'

### Defining the data directories

In addition, we need to define our data directories from which the files will be loaded and to which the resulting file will be stored. Please mind that these need to be changed to the desired directories to be able to work with the data directories.

In [3]:
data_directory_combined_cleaned_files = "C:/Users/laure/OneDrive/Documenten/Bachelor Thesis Data/combined_cleaned_data"
data_directory_location_files = "C:/Users/laure/OneDrive/Documenten/Bachelor Thesis Data/location_data"

## Retrieving the Locations of the Genes

Within this section, the locations of the genes will be retrieved.

#### Loading the 'gene_expression_data_cleaned_sorted.csv' file into this notebook

To start the location retrieval of the genes, we first need to load the file 'gene_expression_data_cleaned_sorted.csv' from the directory 'data_directory_combined_cleaned_files'. This can be achieved by calling the function 'fread()' with as argument the path of the file that should be loaded into this notebook as a data table. To explicitly call the function 'fread()' from the 'data.table' package, the '::' operator is used.

In [4]:
# The path of the gene expression data file 'gene_expression_data_cleaned_sorted.csv' to be loaded into this notebook.
path <- file.path(data_directory_combined_cleaned_files, "gene_expression_data_cleaned_sorted.csv")

# If the 'path' defined above does not point to a file, the execution of this code block is terminated and an error message
# is displayed.
if (!file.exists(path)) {
  stop("File not found: ", path)
}

# Loading the gene expression data as a data table into this notebook by calling the function 'fread()'.
gene_expression_data <- data.table::fread(path)

cat("The gene expression data:")
gene_expression_data

The gene_expression data:

Gene ID            Gene Name    TCGA-06-0125-01A-01 TCGA-06-0125-02A-11
1     ENSG00000000003.15 TSPAN6        76.7833             82.9215           
2     ENSG00000000005.6  TNMD           0.4035              0.4189           
3     ENSG00000000419.13 DPM1          97.4399             63.4521           
4     ENSG00000000457.14 SCYL3          6.5428              5.4929           
5     ENSG00000000460.17 C1orf112       5.9849              3.1369           
6     ENSG00000000938.13 FGR            7.0651             16.4290           
7     ENSG00000000971.16 CFH           16.9301             16.4273           
8     ENSG00000001036.14 FUCA2         63.7275             66.9871           
9     ENSG00000001084.13 GCLC          14.5107             22.8885           
10    ENSG00000001167.14 NFYA          24.2783             18.1955           
11    ENSG00000001460.18 STPG1          0.9795              1.4115           
12    ENSG00000001461.17 NIPAL3        22.7208             23.8983           
13    ENSG00000001497.18 LAS1L         21.7707             11.3770           
14    ENSG00000001561.7  ENPP4          2.4844             11.5270           
15    ENSG00000001617.12 SEMA3F        17.5372              9.6279           
16    ENSG00000001626.16 CFTR           1.0931              0.2666           
17    ENSG00000001629.10 ANKIB1        77.3480             86.7573           
18    ENSG00000001630.17 CYP51A1        7.2138              7.4593           
19    ENSG00000001631.16 KRIT1          8.1108              5.1686           
20    ENSG00000002016.18 RAD52         27.1265              8.1607           
21    ENSG00000002330.14 BAD           30.0710             28.8590           
22    ENSG00000002549.12 LAP3         163.2690            168.4556           
23    ENSG00000002586.20 CD99         446.2676            699.5910           
24    ENSG00000002587.10 HS3ST1        25.7199             12.0117           
25    ENSG00000002745.13 WNT16          0.2509              0.5142           
26    ENSG00000002746.15 HECW1          0.7906              1.1474           
27    ENSG00000002834.18 LASP1        109.6784            102.2343           
28    ENSG00000002919.15 SNX11         21.7745             22.5914           
29    ENSG00000002933.9  TMEM176A      21.0015             60.5924           
30    ENSG00000003056.8  M6PR          68.8098             76.7790           
⋮     ⋮                  ⋮            ⋮                   ⋮                  
20408 ENSG00000288009.1  AL353135.2    2.5391              1.8581            
20409 ENSG00000288011.1  AC024597.1    0.0765              0.2723            
20410 ENSG00000288012.1  AP003307.1    0.8613              2.3361            
20411 ENSG00000288033.1  AC137894.4    3.3118              0.4679            
20412 ENSG00000288041.1  AC092819.3    0.0344              0.0000            
20413 ENSG00000288045.1  AL352979.4    2.2336              2.0959            
20414 ENSG00000288048.1  AC104088.3    6.1089              3.5619            
20415 ENSG00000288060.1  AL355338.1    3.7121              1.9707            
20416 ENSG00000288062.1  AL136981.3    4.0787              1.0891            
20417 ENSG00000288066.1  AC097448.1   21.1786             18.4802            
20418 ENSG00000288088.1  AL606923.2    1.9686              4.7740            
20419 ENSG00000288095.1  AC005618.4    0.4936              0.4686            
20420 ENSG00000288156.1  AC104530.1    2.2825              4.0968            
20421 ENSG00000288162.1  AL596442.4    0.0869              0.1031            
20422 ENSG00000288234.1  BX255925.4    0.7316              0.0000            
20423 ENSG00000288398.1  AL109627.1   13.7856             18.6825            
20424 ENSG00000288525.1  AC011228.3    0.1291              0.0000            
20425 ENSG00000288538.1  AP002985.1    5.6475              0.8063            
20426 ENSG00000288545.1  AC023421.2    0.9165              1.4501            
20427 ENSG00000288558.2  DUS

Since we only need the names of the genes and not the gene expression values for the samples to be able to retrieve the location of the genes, we only need the column 'Gene ID' from the data table 'gene_expression_data'. This can be achieved by using the R notation 'data_table$column_name'.

In [5]:
# Retrieving the genes by accessing the elements in the column 'Gene ID'.
genes <- gene_expression_data$'Gene ID'

cat("The genes:")
genes

The genes:

[1] "ENSG00000000003.15" "ENSG00000000005.6"  "ENSG00000000419.13"
    [4] "ENSG00000000457.14" "ENSG00000000460.17" "ENSG00000000938.13"
    [7] "ENSG00000000971.16" "ENSG00000001036.14" "ENSG00000001084.13"
   [10] "ENSG00000001167.14" "ENSG00000001460.18" "ENSG00000001461.17"
   [13] "ENSG00000001497.18" "ENSG00000001561.7"  "ENSG00000001617.12"
   [16] "ENSG00000001626.16" "ENSG00000001629.10" "ENSG00000001630.17"
   [19] "ENSG00000001631.16" "ENSG00000002016.18" "ENSG00000002330.14"
   [22] "ENSG00000002549.12" "ENSG00000002586.20" "ENSG00000002587.10"
   [25] "ENSG00000002745.13" "ENSG00000002746.15" "ENSG00000002834.18"
   [28] "ENSG00000002919.15" "ENSG00000002933.9"  "ENSG00000003056.8" 
   [31] "ENSG00000003096.14" "ENSG00000003137.8"  "ENSG00000003147.19"
   [34] "ENSG00000003249.15" "ENSG00000003393.15" "ENSG00000003400.15"
   [37] "ENSG00000003402.20" "ENSG00000003436.16" "ENSG00000003509.16"
   [40] "ENSG00000003756.17" "ENSG00000003987.14" "ENSG00000003989.18"
   [43] "ENSG00000004059.11" "ENSG00000004139.14" "ENSG00000004142.12"
   [46] "ENSG00000004399.13" "ENSG00000004455.17" "ENSG00000004468.13"
   [49] "ENSG00000004478.8"  "ENSG00000004487.17" "ENSG00000004534.15"
   [52] "ENSG00000004660.15" "ENSG00000004700.16" "ENSG00000004766.17"
   [55] "ENSG00000004776.13" "ENSG00000004777.18" "ENSG00000004779.10"
   [58] "ENSG00000004799.8"  "ENSG00000004838.14" "ENSG00000004848.8" 
   [61] "ENSG00000004864.14" "ENSG00000004866.22" "ENSG00000004897.12"
   [64] "ENSG00000004961.15" "ENSG00000004975.12" "ENSG00000005007.13"
   [67] "ENSG00000005020.13" "ENSG00000005022.6"  "ENSG00000005059.16"
   [70] "ENSG00000005073.6"  "ENSG00000005075.15" "ENSG00000005100.13"
   [73] "ENSG00000005102.14" "ENSG00000005108.16" "ENSG00000005156.12"
   [76] "ENSG00000005175.10" "ENSG00000005189.20" "ENSG00000005194.15"
   [79] "ENSG00000005206.17" "ENSG00000005238.20" "ENSG00000005243.10"
   [82] "ENSG00000005249.13" "ENSG00000005302.19" "ENSG00000005339.15"
   [85] "ENSG00000005379.17" "ENSG00000005436.14" "ENSG00000005448.17"
   [88] "ENSG00000005469.12" "ENSG00000005471.19" "ENSG00000005483.21"
   [91] "ENSG00000005486.17" "ENSG00000005513.10" "ENSG00000005700.15"
   [94] "ENSG00000005801.18" "ENSG00000005810.18" "ENSG00000005812.11"
   [97] "ENSG00000005844.19" "ENSG00000005882.12" "ENSG00000005884.18"
  [100] "ENSG00000005889.16" "ENSG00000005893.16" "ENSG00000006007.12"
  [103] "ENSG00000006015.18" "ENSG00000006016.11" "ENSG00000006025.12"
  [106] "ENSG00000006042.12" "ENSG00000006047.13" "ENSG00000006062.17"
  [109] "ENSG00000006071.15" "ENSG00000006116.4"  "ENSG00000006118.15"
  [112] "ENSG00000006125.18" "ENSG00000006128.12" "ENSG00000006194.10"
  [115] "ENSG00000006210.7"  "ENSG00000006282.21" "ENSG00000006283.18"
  [118] "ENSG00000006327.14" "ENSG00000006377.11" "ENSG00000006432.15"
  [121] "ENSG00000006451.8"  "ENSG00000006453.14" "ENSG00000006459.11"
  [124] "ENSG00000006468.14" "ENSG00000006530.18" "ENSG00000006534.16"
  [127] "ENSG00000006576.16" "ENSG00000006606.9"  "ENSG00000006607.14"
  [130] "ENSG00000006611.17" "ENSG00000006625.18" "ENSG00000006634.8" 
  [133] "ENSG00000006638.13" "ENSG00000006652.15" "ENSG00000006695.12"
  [136] "ENSG00000006704.11" "ENSG00000006712.15" "ENSG00000006715.16"
  [139] "ENSG00000006740.17" "ENSG00000006744.19" "ENSG00000006747.15"
  [142] "ENSG00000006756.16" "ENSG00000006757.12" "ENSG00000006831.10"
  [145] "ENSG00000007047.15" "ENSG00000007062.12" "ENSG00000007080.11"
  [148] "ENSG00000007129.18" "ENSG00000007168.14" "ENSG00000007171.18"
  [151] "ENSG00000007174.18" "ENSG00000007202.15" "ENSG00000007237.19"
  [154] "ENSG00000007255.10" "ENSG00000007264.15" "ENSG00000007341.19"
  [157] "ENSG00000007350.17" "ENSG00000007372.24" "ENSG00000007376.8" 
  [160] "ENSG00000007384.15" "ENSG00000007392.17" "ENSG00000007402.12"
  [163] "ENSG00000007516.14" "ENSG00000007520.4"  "ENSG00000007541.17"
  [166] "ENSG00000007545.16" "ENSG00000007866.22" "ENSG00000007908.16"
  [169] "ENSG00000007923.16"

Since each of the genes above features the actual gene id followed by the version ID after the dot, we can shorten the gene IDs by removing the version ID. We can do this, since the database (Ensembl BioMart database) from which we will be retrieving the gene annotation data from later in this notebook does not explicitly contain the version ID but it will always return the latest version of the gene IDs. To achieve this, we can call the function 'gsub()' which replaces the part of the gene IDs that contain a dot followed by any number of values with an empty string such that only the part of the gene IDs remain that actually encode the gene.

In [6]:
# Replacing the part of the gene IDs that contain a dot followed by any number of values with an empty string such that only 
# the part of the gene IDs remain that actually encode the gene.
genes <- gsub("\\.\\d+$", "", genes)

cat("The genes after replacing the part of the gene IDs that contain a dot followed by any number of values with an empty string such that only the part of the gene IDs remain that actually encode the gene:")
genes

The genes after replacing the part of the gene IDs that contain a dot followed by any number of values with an empty string such that only the part of the gene IDs remain that actually encode the gene:

[1] "ENSG00000000003" "ENSG00000000005" "ENSG00000000419" "ENSG00000000457"
    [5] "ENSG00000000460" "ENSG00000000938" "ENSG00000000971" "ENSG00000001036"
    [9] "ENSG00000001084" "ENSG00000001167" "ENSG00000001460" "ENSG00000001461"
   [13] "ENSG00000001497" "ENSG00000001561" "ENSG00000001617" "ENSG00000001626"
   [17] "ENSG00000001629" "ENSG00000001630" "ENSG00000001631" "ENSG00000002016"
   [21] "ENSG00000002330" "ENSG00000002549" "ENSG00000002586" "ENSG00000002587"
   [25] "ENSG00000002745" "ENSG00000002746" "ENSG00000002834" "ENSG00000002919"
   [29] "ENSG00000002933" "ENSG00000003056" "ENSG00000003096" "ENSG00000003137"
   [33] "ENSG00000003147" "ENSG00000003249" "ENSG00000003393" "ENSG00000003400"
   [37] "ENSG00000003402" "ENSG00000003436" "ENSG00000003509" "ENSG00000003756"
   [41] "ENSG00000003987" "ENSG00000003989" "ENSG00000004059" "ENSG00000004139"
   [45] "ENSG00000004142" "ENSG00000004399" "ENSG00000004455" "ENSG00000004468"
   [49] "ENSG00000004478" "ENSG00000004487" "ENSG00000004534" "ENSG00000004660"
   [53] "ENSG00000004700" "ENSG00000004766" "ENSG00000004776" "ENSG00000004777"
   [57] "ENSG00000004779" "ENSG00000004799" "ENSG00000004838" "ENSG00000004848"
   [61] "ENSG00000004864" "ENSG00000004866" "ENSG00000004897" "ENSG00000004961"
   [65] "ENSG00000004975" "ENSG00000005007" "ENSG00000005020" "ENSG00000005022"
   [69] "ENSG00000005059" "ENSG00000005073" "ENSG00000005075" "ENSG00000005100"
   [73] "ENSG00000005102" "ENSG00000005108" "ENSG00000005156" "ENSG00000005175"
   [77] "ENSG00000005189" "ENSG00000005194" "ENSG00000005206" "ENSG00000005238"
   [81] "ENSG00000005243" "ENSG00000005249" "ENSG00000005302" "ENSG00000005339"
   [85] "ENSG00000005379" "ENSG00000005436" "ENSG00000005448" "ENSG00000005469"
   [89] "ENSG00000005471" "ENSG00000005483" "ENSG00000005486" "ENSG00000005513"
   [93] "ENSG00000005700" "ENSG00000005801" "ENSG00000005810" "ENSG00000005812"
   [97] "ENSG00000005844" "ENSG00000005882" "ENSG00000005884" "ENSG00000005889"
  [101] "ENSG00000005893" "ENSG00000006007" "ENSG00000006015" "ENSG00000006016"
  [105] "ENSG00000006025" "ENSG00000006042" "ENSG00000006047" "ENSG00000006062"
  [109] "ENSG00000006071" "ENSG00000006116" "ENSG00000006118" "ENSG00000006125"
  [113] "ENSG00000006128" "ENSG00000006194" "ENSG00000006210" "ENSG00000006282"
  [117] "ENSG00000006283" "ENSG00000006327" "ENSG00000006377" "ENSG00000006432"
  [121] "ENSG00000006451" "ENSG00000006453" "ENSG00000006459" "ENSG00000006468"
  [125] "ENSG00000006530" "ENSG00000006534" "ENSG00000006576" "ENSG00000006606"
  [129] "ENSG00000006607" "ENSG00000006611" "ENSG00000006625" "ENSG00000006634"
  [133] "ENSG00000006638" "ENSG00000006652" "ENSG00000006695" "ENSG00000006704"
  [137] "ENSG00000006712" "ENSG00000006715" "ENSG00000006740" "ENSG00000006744"
  [141] "ENSG00000006747" "ENSG00000006756" "ENSG00000006757" "ENSG00000006831"
  [145] "ENSG00000007047" "ENSG00000007062" "ENSG00000007080" "ENSG00000007129"
  [149] "ENSG00000007168" "ENSG00000007171" "ENSG00000007174" "ENSG00000007202"
  [153] "ENSG00000007237" "ENSG00000007255" "ENSG00000007264" "ENSG00000007341"
  [157] "ENSG00000007350" "ENSG00000007372" "ENSG00000007376" "ENSG00000007384"
  [161] "ENSG00000007392" "ENSG00000007402" "ENSG00000007516" "ENSG00000007520"
  [165] "ENSG00000007541" "ENSG00000007545" "ENSG00000007866" "ENSG00000007908"
  [169] "ENSG00000007923" "ENSG00000007933" "ENSG00000007944" "ENSG00000007968"
  [173] "ENSG00000008018" "ENSG00000008056" "ENSG00000008083" "ENSG00000008086"
  [177] "ENSG00000008118" "ENSG00000008130" "ENSG00000008196" "ENSG00000008226"
  [181] "ENSG00000008256" "ENSG00000008277" "ENSG00000008282" "ENSG00000008283"
  [185] "ENSG00000008294" "ENSG00000008300" "ENSG00000008311" "ENSG00000008324"
  [189] "ENSG00000008382" "ENSG00000008394" "ENSG00000008405" "ENSG00000008438"
  [193] "ENSG00000008441" "ENSG00000008513" "ENSG00000008516" "ENSG00000008517"
  [197] "ENSG00000008710" "ENSG00000008735" "ENSG00000008838" "ENSG00000008853"
  [2

Next, we can check whether all the genes are unique to ensure that by removing the version IDs we have not created duplicate gene IDs. This can be achieved by calling the function 'unique()'.

In [7]:
# Checking whether all the genes in the 'genes' array are unique.
unique_genes <- unique(genes)

if (length(unique_genes) == nrow(gene_expression_data)) {
  cat("All genes are unique.")
} else {
  cat("There are duplicated genes.")
}

All genes are unique.

As we can see from the output above, all the genes are unique even after having removed the version IDs.

#### Retrieving the locations

The first step towards retrieving the location data of the genes is to retrieve the annotation information for each gene. First, the Ensembl BioMart database needs to be set up by calling the function 'useMart' which originates from the loaded 'biomaRt' library. 

It is important to note here that the exact locations for the genes will not be the same for every sample we retrieved as the genome between two samples will be different because of duplications and deletions. We can, however, use the reference genome Human Genome version 19 assembly which is the same one that was used to retrieve the locations of the CpG sites as the reference genome is generally considered to be a good estimate for the positions of the genes in the majority of individuals of that species. This is the reference genome that is used within the Ensembl BioMart database.

In [8]:
# Setting up the Ensembl BioMart database to retrieve the gene locations.
ensembl_database <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

Next, we can retrieve the annotation information for each gene by calling the function 'getBM()' which also originates from the loaded 'biomaRt' library. As arguments to this function, we include which database should be used (which is the 'ensembl_database') and which columns should be retrieved. The following six columns are retrieved: 'ensembl_gene_id', 'external_gene_name', 'chromosome_name', 'start_position', 'end_position', and 'strand'.

In [9]:
# Retrieve the gene locations using the getBM function
annotation_genes <- getBM(attributes = c("ensembl_gene_id", "external_gene_name", "chromosome_name", "start_position", "end_position", "strand"), mart = ensembl_database)

# Converting the retrieved data frame to a data table to improve readability.
annotation_genes <- data.table::as.data.table(annotation_genes)

cat("The annotation information for the genes present in the Ensembl BioMart database:")
annotation_genes

The annotation information for the genes present in the Ensembl BioMart database:

ensembl_gene_id external_gene_name chromosome_name start_position
1     ENSG00000210049 MT-TF              MT                577         
2     ENSG00000211459 MT-RNR1            MT                648         
3     ENSG00000210077 MT-TV              MT               1602         
4     ENSG00000210082 MT-RNR2            MT               1671         
5     ENSG00000209082 MT-TL1             MT               3230         
6     ENSG00000198888 MT-ND1             MT               3307         
7     ENSG00000210100 MT-TI              MT               4263         
8     ENSG00000210107 MT-TQ              MT               4329         
9     ENSG00000210112 MT-TM              MT               4402         
10    ENSG00000198763 MT-ND2             MT               4470         
11    ENSG00000210117 MT-TW              MT               5512         
12    ENSG00000210127 MT-TA              MT               5587         
13    ENSG00000210135 MT-TN              MT               5657         
14    ENSG00000210140 MT-TC              MT               5761         
15    ENSG00000210144 MT-TY              MT               5826         
16    ENSG00000198804 MT-CO1             MT               5904         
17    ENSG00000210151 MT-TS1             MT               7446         
18    ENSG00000210154 MT-TD              MT               7518         
19    ENSG00000198712 MT-CO2             MT               7586         
20    ENSG00000210156 MT-TK              MT               8295         
21    ENSG00000228253 MT-ATP8            MT               8366         
22    ENSG00000198899 MT-ATP6            MT               8527         
23    ENSG00000198938 MT-CO3             MT               9207         
24    ENSG00000210164 MT-TG              MT               9991         
25    ENSG00000198840 MT-ND3             MT              10059         
26    ENSG00000210174 MT-TR              MT              10405         
27    ENSG00000212907 MT-ND4L            MT              10470         
28    ENSG00000198886 MT-ND4             MT              10760         
29    ENSG00000210176 MT-TH              MT              12138         
30    ENSG00000210184 MT-TS2             MT              12207         
⋮     ⋮               ⋮                  ⋮               ⋮             
69270 ENSG00000225632                    1                54285404     
69271 ENSG00000157216 SSBP3              1                54225432     
69272 ENSG00000143552 NUP210L            1               153992690     
69273 ENSG00000169641 LUZP1              1                23084030     
69274 ENSG00000289014                    1                23167098     
69275 ENSG00000179546 HTR1D              1                23191895     
69276 ENSG00000067208 EVI5               1                92508696     
69277 ENSG00000143774 GUK1               1               228139962     
69278 ENSG00000169991 IFFO2              1                18904280     
69279 ENSG00000198400 NTRK1              1               156815636     
69280 ENSG00000241128 OR14A2             1               247722957     
69281 ENSG00000097021 ACOT7              1                 6264269     
69282 ENSG00000187017 ESPN               1                 6424776     
69283 ENSG00000198216 CACNA1E            1               181317690     
69284 ENSG00000179930 ZNF648             1               182054570     
69285 ENSG00000224810                    1               182062677     
69286 ENSG00000225982                    1               182086551     
69287 ENSG00000228918 LINC01344          1               182096338     
69288 ENSG00000232309                    1               182127297     
69289 ENSG00000289573                    1               182149703     
69290 ENSG00000232096 YPEL5P1            1               182182730     
69291 ENSG00000206764 RNU6-152P          1               182327068     
69292 ENSG00000228664                    1               182328497     
69293 ENSG00000231684 EIF1P3             1    

Now that we have succesfully loaded the annotation information for the genes present on the Human Genome version 19 assembly reference genome, we can check whether indeed all the genes present within the gene expression data stored in the variable 'genes' is also present in the annotation data stored in the variable 'annotation_genes'. This can be achieved by applying the '%in%' operator which in the code below checks whether the 'genes' appear in the 'ensembl_gene_id' column in the 'annotation_genes' data table. If a gene is not present in that column, it will be marked as 'TRUE' within the 'missing_genes' string of characters.

In [10]:
# Checking whether the 'genes' appear in the 'ensembl_gene_id' column in the 'annotation_genes' data table.
missing_genes <- !genes %in% annotation_genes$ensembl_gene_id

# Retrieving the genes which are not present in the 'ensembl_gene_id' column in the 'annotation_genes' data table.
genes_missing <- genes[missing_genes]

# Displaying the missing genes.
if (length(genes_missing) == 0) {
    cat("All the genes are present in the annotation data.")
} else {
    cat("The following genes are not present in the annotation data:\n")
    cat(genes_missing)
    cat("\n\nThe number of genes that are not present in the annotation data:\n")
    cat(length(genes_missing))
}

The following genes are not present in the annotation data:
ENSG00000112096 ENSG00000130723 ENSG00000203812 ENSG00000204092 ENSG00000204805 ENSG00000215271 ENSG00000221995 ENSG00000224739 ENSG00000225178 ENSG00000226380 ENSG00000226403 ENSG00000228139 ENSG00000228906 ENSG00000235245 ENSG00000236166 ENSG00000237838 ENSG00000239467 ENSG00000239665 ENSG00000253878 ENSG00000254615 ENSG00000255633 ENSG00000255823 ENSG00000256045 ENSG00000256427 ENSG00000256618 ENSG00000259834 ENSG00000261490 ENSG00000261534 ENSG00000261737 ENSG00000261963 ENSG00000269028 ENSG00000269894 ENSG00000270030 ENSG00000270178 ENSG00000270195 ENSG00000271043 ENSG00000271870 ENSG00000271895 ENSG00000272040 ENSG00000272196 ENSG00000272370 ENSG00000272551 ENSG00000273301 ENSG00000273837 ENSG00000274031 ENSG00000275560 ENSG00000277050 ENSG00000277203 ENSG00000279400 ENSG00000280374 ENSG00000286699 ENSG00000287116 ENSG00000287686 ENSG00000288617

The number of genes that are not present in the annotation data:
54

As we can see from the output above, there are 54 genes out of 20437 genes from the gene expression data for which no information regarding their location is present in the Ensembl BioMart database. Since this number is not that large as it is only roughly 0.26 percent of the total number of genes, we can discard these genes from all the gene expression datasets which are present in the directory 'data_directory_combined_cleaned_files' as well as discarding them from the array of genes called 'genes'.

Before we delete these genes, we also want to check whether there are any genes which, although they are present in the annotation data, contain some missing data or unexpected data for the columns (information) we want to retrieve: the chromosome, start position, end position, and strand. All the to be deleted genes can then be added to the array 'genes_to_delete' such that we can later delete all of them at once.

In [11]:
# Assigning the genes to be deleted to the array 'genes_to_delete'.
genes_to_delete = genes_missing

##### The chromosome

For the chromosome, we can first of all check whether there are any genes for which there is no information about the chromosome present within the 'annotation_genes'. This can be achieved by finding the subset of rows (genes) within the 'annotation_genes' data table where the gene is of course present in the 'genes' character array and has a missing value for that column. The function 'subset() can help to find these subsets.

In [12]:
# Retrieving the genes for which the column 'chromosome_name' representing the chromosome has a missing value.
missing_genes_chromosome <- subset(annotation_genes, ensembl_gene_id %in% genes & is.na(chromosome_name))

# Checking whether the number of genes in the 'missing_genes_chromosome' is equal to 0.
if (nrow(missing_genes_chromosome) == 0) {
    cat("None of the genes present in the 'genes' character array have a missing value for the 'chromosome_name' column.\n")
} else {
    cat("The following genes that are present in the 'genes' character array have a missing value for the 'chromosome_name' column:\n")
    print(missing_genes_chromosome)
    cat("\n\nThe number of genes that have a missing value for the 'chromosome_name' column.:\n")
    cat(nrow(missing_genes_chromosome))
}

None of the genes present in the 'genes' character array have a missing value for the 'chromosome_name' column.


As we can see from the output above, none of the genes present in the 'genes' character array have a missing value for the 'chromosome_name' column of the 'annotation_genes' data table. Next, we need to verify whether all the values in the 'chromosome_name' column correspond to values that we would expect to see. In this case, we expect the values to be between 1 and 22 (as we also want to exclude the sex chromosomes).

In [13]:
# Checking whether all the values in the 'chromosome_name' column correspond to values that we would expect to see. In this 
# case, we expect the values to be between 1 and 22 (as we also want to exclude the sex chromosomes).
expected_chromosomes <- c(1:22)
genes_unexpected_chromosome <- subset(annotation_genes, ensembl_gene_id %in% genes & !chromosome_name %in% expected_chromosomes)

# Checking whether the number of genes in the 'genes_unexpected_chromosome' is equal to 0.
if (nrow(genes_unexpected_chromosome) == 0) {
    cat("None of the genes present in the 'genes' character array have an unexpected value for the 'chromosome_name' column.\n")
} else {
    cat("The following genes that are present in the 'genes' character array have an unexpected value for the 'chromosome_name' column:\n")
    print(genes_unexpected_chromosome)
    cat("\n\nThe number of genes that have an unexpected value for the 'chromosome_name' column.:\n")
    cat(nrow(genes_unexpected_chromosome))
}

The following genes that are present in the 'genes' character array have an unexpected value for the 'chromosome_name' column:
     ensembl_gene_id external_gene_name chromosome_name start_position
  1: ENSG00000210049              MT-TF              MT            577
  2: ENSG00000211459            MT-RNR1              MT            648
  3: ENSG00000210082            MT-RNR2              MT           1671
  4: ENSG00000209082             MT-TL1              MT           3230
  5: ENSG00000198888             MT-ND1              MT           3307
 ---                                                                  
748: ENSG00000101871               MID1               X       10445310
749: ENSG00000124313             IQSEC2               X       53225828
750: ENSG00000077264               PAK3               X      110944285
751: ENSG00000147394             ZNF185               X      152898067
752: ENSG00000126756                UXT               X       47651796
     end_position str

As we can see from the output above, there are 752 genes present in the 'genes' character array which have an unexpected value for the 'chromosome_name' column of the 'annotation_genes' data table. This number is so high as most of them are located on the X and Y chromosomes and on the mitochondrial DNA which contains a single circular chromosome. Since we do not want to investigate the genes located on the X and Y chromosome and on the mitochondrial DNA, we can add them to the 'genes_to_delete' array such that these are deleted later as well.

In [14]:
# Adding the 'genes_unexpected_chromosome' to the 'genes_to_delete' array. 
genes_to_delete <- c(genes_to_delete, genes_unexpected_chromosome$ensembl_gene_id)

##### The start position

For the start position, we can first of all check whether there are any genes for which there is no information about the start position present within the 'annotation_genes'. This can be achieved by finding the subset of rows (genes) within the 'annotation_genes' data table where the gene is of course present in the 'genes' character array and has a missing value for that column. The function 'subset() can help to find these subsets.

In [15]:
# Retrieving the genes for which the column 'start_position' representing the start position has a missing value.
missing_genes_start_position <- subset(annotation_genes, ensembl_gene_id %in% genes & is.na(start_position))

# Checking whether the number of genes in the 'missing_genes_start_position' is equal to 0.
if (nrow(missing_genes_start_position) == 0) {
    cat("None of the genes present in the 'genes' character array have a missing value for the 'start_position' column.\n")
} else {
    cat("The following genes that are present in the 'genes' character array have a missing value for the 'start_position' column:\n")
    print(missing_genes_start_position)
    cat("\n\nThe number of genes that have a missing value for the 'start_position' column.:\n")
    cat(nrow(missing_genes_start_position))
}

None of the genes present in the 'genes' character array have a missing value for the 'start_position' column.


As we can see from the output above, none of the genes present in the 'genes' character array have a missing value for the 'start_position' column of the 'annotation_genes' data table. Next, we need to verify whether all the values in the 'start_position' column correspond to values that we would expect to see. In this case, we expect the values to be higher than 0 at all times and that the value is always lower than the value in the 'end_position' column.

In [16]:
# Checking whether all the values in the 'start_position' column correspond to values that we would expect to see. In this 
# case, we expect the values to be higher than 0 at all times and that the value is always lower than the value in the 
# 'end_position' column.
genes_unexpected_start_position <- subset(annotation_genes, ensembl_gene_id %in% genes & !start_position > 0 & !start_position < end_position)

# Checking whether the number of genes in the 'genes_unexpected_start_position' is equal to 0.
if (nrow(genes_unexpected_start_position) == 0) {
    cat("None of the genes present in the 'genes' character array have an unexpected value for the 'start_position' column.\n")
} else {
    cat("The following genes that are present in the 'genes' character array have an unexpected value for the 'start_position' column:\n")
    print(genes_unexpected_start_position)
    cat("\n\nThe number of genes that have an unexpected value for the 'start_position' column.:\n")
    cat(nrow(genes_unexpected_start_position))
}

None of the genes present in the 'genes' character array have an unexpected value for the 'start_position' column.


As we can see from the output above, none of the genes present in the 'genes' character array have an unexpected value for the 'start_position' column of the 'annotation_genes' data table. Therefore, no additional genes need to be deleted.

##### The end position

For the end position, we can first of all check whether there are any genes for which there is no information about the end position present within the 'annotation_genes'. This can be achieved by finding the subset of rows (genes) within the 'annotation_genes' data table where the gene is of course present in the 'genes' character array and has a missing value for that column. The function 'subset() can help to find these subsets.

In [17]:
# Retrieving the genes for which the column 'end_position' representing the end position has a missing value.
missing_genes_end_position <- subset(annotation_genes, ensembl_gene_id %in% genes & is.na(end_position))

# Checking whether the number of genes in the 'missing_genes_end_position' is equal to 0.
if (nrow(missing_genes_end_position) == 0) {
    cat("None of the genes present in the 'genes' character array have a missing value for the 'end_position' column.\n")
} else {
    cat("The following genes that are present in the 'genes' character array have a missing value for the 'end_position' column:\n")
    print(missing_genes_end_position)
    cat("\n\nThe number of genes that have a missing value for the 'end_position' column.:\n")
    cat(nrow(missing_genes_end_position))
}

None of the genes present in the 'genes' character array have a missing value for the 'end_position' column.


As we can see from the output above, none of the genes present in the 'genes' character array have a missing value for the 'end_position' column of the 'annotation_genes' data table. Next, we need to verify whether all the values in the 'end_position' column correspond to values that we would expect to see. In this case, we expect the values to be higher than 0 at all times and that the value is always higher than the value in the 'start_position' column.

In [18]:
# Checking whether all the values in the 'end_position' column correspond to values that we would expect to see. In this 
# case, we expect the values to be higher than 0 at all times and that the value is always higher than the value in the 
# 'start_position' column.
genes_unexpected_end_position <- subset(annotation_genes, ensembl_gene_id %in% genes & !end_position > 0 & !start_position < end_position)

# Checking whether the number of genes in the 'genes_unexpected_end_position' is equal to 0.
if (nrow(genes_unexpected_end_position) == 0) {
    cat("None of the genes present in the 'genes' character array have an unexpected value for the 'end_position' column.\n")
} else {
    cat("The following genes that are present in the 'genes' character array have an unexpected value for the 'end_position' column:\n")
    print(genes_unexpected_end_position)
    cat("\n\nThe number of genes that have an unexpected value for the 'end_position' column.:\n")
    cat(nrow(genes_unexpected_end_position))
}

None of the genes present in the 'genes' character array have an unexpected value for the 'end_position' column.


As we can see from the output above, none of the genes present in the 'genes' character array have an unexpected value for the 'end_position' column of the 'annotation_genes' data table. Therefore, no additional genes need to be deleted.

##### The strand

For the strand, we can first of all check whether there are any genes for which there is no information about the strand present within the 'annotation_genes'. This can be achieved by finding the subset of rows (genes) within the 'annotation_genes' data table where the gene is of course present in the 'genes' character array and has a missing value for that column. The function 'subset() can help to find these subsets.

In [19]:
# Retrieving the genes for which the column 'strand' representing the strand has a missing value.
missing_genes_strand <- subset(annotation_genes, ensembl_gene_id %in% genes & is.na(strand))

# Checking whether the number of genes in the 'missing_genes_strand' is equal to 0.
if (nrow(missing_genes_strand) == 0) {
    cat("None of the genes present in the 'genes' character array have a missing value for the 'strand' column.\n")
} else {
    cat("The following genes that are present in the 'genes' character array have a missing value for the 'strand' column:\n")
    print(missing_genes_strand)
    cat("\n\nThe number of genes that have a missing value for the 'strand' column.:\n")
    cat(nrow(missing_genes_strand))
}

None of the genes present in the 'genes' character array have a missing value for the 'strand' column.


As we can see from the output above, none of the genes present in the 'genes' character array have a missing value for the 'strand' column of the 'annotation_genes' data table. Next, we need to verify whether all the values in the 'strand' column correspond to values that we would expect to see. In this case, we expect the values to be equal to either 1 or -1.

In [20]:
# Checking whether all the values in the 'strand' column correspond to values that we would expect to see. In this case, we
# expect the values to be equal to either 1 or -1.
genes_unexpected_strand <- subset(annotation_genes, ensembl_gene_id %in% genes & !(strand != -1 | strand != 1))

# Checking whether the number of genes in the 'genes_unexpected_strand' is equal to 0.
if (nrow(genes_unexpected_strand) == 0) {
    cat("None of the genes present in the 'genes' character array have an unexpected value for the 'strand' column.\n")
} else {
    cat("The following genes that are present in the 'genes' character array have an unexpected value for the 'strand' column:\n")
    print(genes_unexpected_strand)
    cat("\n\nThe number of genes that have an unexpected value for the 'strand' column.:\n")
    cat(nrow(genes_unexpected_strand))
}

None of the genes present in the 'genes' character array have an unexpected value for the 'strand' column.


As we can see from the output above, none of the genes present in the 'genes' character array have an unexpected value for the 'strand' column of the 'annotation_genes' data table. Therefore, no additional genes need to be deleted.

<br></br>
<br></br>
We can retrieve for how many genes there is some location information missing or unexpected values occur within the desired columns by calling the function 'length()'.

In [21]:
cat("The number of genes for which there is some location information missing or unexpected values occur within the desired columns causing us to delete the genes:\n")
length(genes_to_delete)

The number of genes for which there is some location information missing or unexpected values occur within the desired columns causing us to delete the genes:


[1] 806

As we can see from the output above, there are 806 genes for which there is some location information missing or unexpected values occur within the desired columns. These genes are deleted from the gene expression datasets and the array 'genes' below.

##### Discarding the 806 genes from all the gene expression datasets

__The file 'gene_expression_data_cleaned_sorted.csv':__

To remove the 806 genes present in the array 'genes_to_delete' from the file 'gene_expression_data_cleaned_sorted.csv', we can alter the 'gene_expression_data' data table to delete the rows that represent these genes. This can be achieved by indexing the 'gene_expression_data' data table based on whether the genes appear within the 'genes_to_delete' array.

In [22]:
# Removing the genes present in the 'genes_to_delete' array from the 'gene_expression_data' data table by indexing the 
# 'gene_expression_data' data table based on whether the genes appear within the 'genes_to_delete' array.
gene_expression_data_genes_removed <- gene_expression_data[!(sub("\\..*", "", gene_expression_data$"Gene ID") %in% genes_to_delete),]

print("The gene expression data after the genes have been removed:")
gene_expression_data_genes_removed

[1] "The gene expression data after the genes have been removed:"


Gene ID            Gene Name    TCGA-06-0125-01A-01 TCGA-06-0125-02A-11
1     ENSG00000000419.13 DPM1          97.4399             63.4521           
2     ENSG00000000457.14 SCYL3          6.5428              5.4929           
3     ENSG00000000460.17 C1orf112       5.9849              3.1369           
4     ENSG00000000938.13 FGR            7.0651             16.4290           
5     ENSG00000000971.16 CFH           16.9301             16.4273           
6     ENSG00000001036.14 FUCA2         63.7275             66.9871           
7     ENSG00000001084.13 GCLC          14.5107             22.8885           
8     ENSG00000001167.14 NFYA          24.2783             18.1955           
9     ENSG00000001460.18 STPG1          0.9795              1.4115           
10    ENSG00000001461.17 NIPAL3        22.7208             23.8983           
11    ENSG00000001561.7  ENPP4          2.4844             11.5270           
12    ENSG00000001617.12 SEMA3F        17.5372              9.6279           
13    ENSG00000001626.16 CFTR           1.0931              0.2666           
14    ENSG00000001629.10 ANKIB1        77.3480             86.7573           
15    ENSG00000001630.17 CYP51A1        7.2138              7.4593           
16    ENSG00000001631.16 KRIT1          8.1108              5.1686           
17    ENSG00000002016.18 RAD52         27.1265              8.1607           
18    ENSG00000002330.14 BAD           30.0710             28.8590           
19    ENSG00000002549.12 LAP3         163.2690            168.4556           
20    ENSG00000002587.10 HS3ST1        25.7199             12.0117           
21    ENSG00000002745.13 WNT16          0.2509              0.5142           
22    ENSG00000002746.15 HECW1          0.7906              1.1474           
23    ENSG00000002834.18 LASP1        109.6784            102.2343           
24    ENSG00000002919.15 SNX11         21.7745             22.5914           
25    ENSG00000002933.9  TMEM176A      21.0015             60.5924           
26    ENSG00000003056.8  M6PR          68.8098             76.7790           
27    ENSG00000003137.8  CYP26B1        1.9444              6.0417           
28    ENSG00000003147.19 ICA1          18.5672              8.1949           
29    ENSG00000003249.15 DBNDD1        72.4181             52.6607           
30    ENSG00000003393.15 ALS2          19.1262             18.6268           
⋮     ⋮                  ⋮            ⋮                   ⋮                  
19602 ENSG00000288002.1  AC091912.3    3.2311              3.5769            
19603 ENSG00000288009.1  AL353135.2    2.5391              1.8581            
19604 ENSG00000288011.1  AC024597.1    0.0765              0.2723            
19605 ENSG00000288012.1  AP003307.1    0.8613              2.3361            
19606 ENSG00000288033.1  AC137894.4    3.3118              0.4679            
19607 ENSG00000288041.1  AC092819.3    0.0344              0.0000            
19608 ENSG00000288045.1  AL352979.4    2.2336              2.0959            
19609 ENSG00000288048.1  AC104088.3    6.1089              3.5619            
19610 ENSG00000288060.1  AL355338.1    3.7121              1.9707            
19611 ENSG00000288062.1  AL136981.3    4.0787              1.0891            
19612 ENSG00000288066.1  AC097448.1   21.1786             18.4802            
19613 ENSG00000288088.1  AL606923.2    1.9686              4.7740            
19614 ENSG00000288095.1  AC005618.4    0.4936              0.4686            
19615 ENSG00000288156.1  AC104530.1    2.2825              4.0968            
19616 ENSG00000288162.1  AL596442.4    0.0869              0.1031            
19617 ENSG00000288234.1  BX255925.4    0.7316              0.0000            
19618 ENSG00000288398.1  AL109627.1   13.7856             18.6825            
19619 ENSG00000288525.1  AC011228.3    0.1291              0.0000            
19620 ENSG00000288538.1  AP002985.1    5.6475              0.8063            
19621 ENSG00000288545.1  AC0

Next, we can also replace the part of the gene IDs present in the 'gene_expression_data_genes_removed' data table that contain a dot followed by any number of values with an empty string such that only the part of the gene IDs remain that actually encode the gene. This would allow us to later retrieve information about the genes present in the 'genes_location_data' data table, which will be defined later, directly by comparing the IDs of the gene rather than having to remove some part of one of the strings first.

In [23]:
# Replacing the part of the gene IDs present in the 'gene_expression_data_genes_removed' data table that contain a dot 
# followed by any number of values with an empty string such that only the part of the gene IDs remain that actually encode 
# the gene.
gene_expression_data_genes_removed$'Gene ID' <- gsub("\\.\\d+$", "", gene_expression_data_genes_removed$'Gene ID')

print("The gene expression data after the gene IDs have been replaced:")
gene_expression_data_genes_removed

[1] "The gene expression data after the gene IDs have been replaced:"


Gene ID         Gene Name    TCGA-06-0125-01A-01 TCGA-06-0125-02A-11
1     ENSG00000000419 DPM1          97.4399             63.4521           
2     ENSG00000000457 SCYL3          6.5428              5.4929           
3     ENSG00000000460 C1orf112       5.9849              3.1369           
4     ENSG00000000938 FGR            7.0651             16.4290           
5     ENSG00000000971 CFH           16.9301             16.4273           
6     ENSG00000001036 FUCA2         63.7275             66.9871           
7     ENSG00000001084 GCLC          14.5107             22.8885           
8     ENSG00000001167 NFYA          24.2783             18.1955           
9     ENSG00000001460 STPG1          0.9795              1.4115           
10    ENSG00000001461 NIPAL3        22.7208             23.8983           
11    ENSG00000001561 ENPP4          2.4844             11.5270           
12    ENSG00000001617 SEMA3F        17.5372              9.6279           
13    ENSG00000001626 CFTR           1.0931              0.2666           
14    ENSG00000001629 ANKIB1        77.3480             86.7573           
15    ENSG00000001630 CYP51A1        7.2138              7.4593           
16    ENSG00000001631 KRIT1          8.1108              5.1686           
17    ENSG00000002016 RAD52         27.1265              8.1607           
18    ENSG00000002330 BAD           30.0710             28.8590           
19    ENSG00000002549 LAP3         163.2690            168.4556           
20    ENSG00000002587 HS3ST1        25.7199             12.0117           
21    ENSG00000002745 WNT16          0.2509              0.5142           
22    ENSG00000002746 HECW1          0.7906              1.1474           
23    ENSG00000002834 LASP1        109.6784            102.2343           
24    ENSG00000002919 SNX11         21.7745             22.5914           
25    ENSG00000002933 TMEM176A      21.0015             60.5924           
26    ENSG00000003056 M6PR          68.8098             76.7790           
27    ENSG00000003137 CYP26B1        1.9444              6.0417           
28    ENSG00000003147 ICA1          18.5672              8.1949           
29    ENSG00000003249 DBNDD1        72.4181             52.6607           
30    ENSG00000003393 ALS2          19.1262             18.6268           
⋮     ⋮               ⋮            ⋮                   ⋮                  
19602 ENSG00000288002 AC091912.3    3.2311              3.5769            
19603 ENSG00000288009 AL353135.2    2.5391              1.8581            
19604 ENSG00000288011 AC024597.1    0.0765              0.2723            
19605 ENSG00000288012 AP003307.1    0.8613              2.3361            
19606 ENSG00000288033 AC137894.4    3.3118              0.4679            
19607 ENSG00000288041 AC092819.3    0.0344              0.0000            
19608 ENSG00000288045 AL352979.4    2.2336              2.0959            
19609 ENSG00000288048 AC104088.3    6.1089              3.5619            
19610 ENSG00000288060 AL355338.1    3.7121              1.9707            
19611 ENSG00000288062 AL136981.3    4.0787              1.0891            
19612 ENSG00000288066 AC097448.1   21.1786             18.4802            
19613 ENSG00000288088 AL606923.2    1.9686              4.7740            
19614 ENSG00000288095 AC005618.4    0.4936              0.4686            
19615 ENSG00000288156 AC104530.1    2.2825              4.0968            
19616 ENSG00000288162 AL596442.4    0.0869              0.1031            
19617 ENSG00000288234 BX255925.4    0.7316              0.0000            
19618 ENSG00000288398 AL109627.1   13.7856             18.6825            
19619 ENSG00000288525 AC011228.3    0.1291              0.0000            
19620 ENSG00000288538 AP002985.1    5.6475              0.8063            
19621 ENSG00000288545 AC023421.2    0.9165              1.4501            
19622 ENSG00000288558 DUS4L-BCAP29  9.1356              6.0041            
19623 ENSG00000288559 AC016394.

To be sure, we can check whether we have not created any duplicate genes by removing part of the gene IDs. This can be achieved by calling the function 'unique()' which returns the number of unique records and check whether this is equal to the number of records present in the 'gene_expression_data_genes_removed' data table. 

In [24]:
# Checking whether all the gene IDs present in the 'Gene ID' column of the 'gene_expression_data_genes_removed' data table
# are unique.
unique_genes <- unique(gene_expression_data_genes_removed$'Gene ID')

if (length(unique_genes) == nrow(gene_expression_data_genes_removed)) {
  cat("All genes are unique.")
} else {
  cat("There are duplicated genes.")
}

All genes are unique.

In addition, we can also check whether any of the gene IDs present in the 'Gene ID' column of the 'gene_expression_data_genes_removed' data table can not be mapped to a gene ID in the 'annotation_genes' data table.

In [25]:
# Checking whether any of the gene IDs present in the 'Gene ID' column of the 'gene_expression_data_genes_removed' data 
# table can not be mapped to a gene ID in the 'annotation_genes' data table.
gene_ids_not_mapped <- !gene_expression_data_genes_removed$'Gene ID' %in% annotation_genes$ensembl_gene_id

# Retrieving the gene IDs which can not be mapped to a gene ID which are present in the 'ensembl_gene_id' column of the 
# 'annotation_genes' data table.
gene_ids <- gene_expression_data_genes_removed$'Gene ID'[gene_ids_not_mapped]

# Displaying the gene IDs that cannot be mapped to a gene ID in the annotation data.
if (length(gene_ids) == 0) {
    cat("All the gene IDs can be mapped to a gene ID in the annotation data.")
} else {
    cat("The following gene IDs cannot be mapped to a gene ID in the annotation data:\n")
    cat(gene_ids)
    cat("\n\nThe number of gene IDs that cannot be mapped to a gene ID in the annotation data:\n")
    cat(length(gene_ids))
}

All the gene IDs can be mapped to a gene ID in the annotation data.

As we can see from the output above, all of the gene IDs present in the 'Gene ID' column of the 'gene_expression_data_genes_removed' data table can be mapped to a gene ID in the 'annotation_genes' data table.

Next, we can store the resulting data table 'gene_expression_data_genes_removed' featuring this information. This can be achieved by calling the function 'fwrite()' from the 'data.table' library which takes as arguments the data table to be stored and the location where the data table should be stored.

In [26]:
# The path where the 'gene_expression_data_genes_removed' data table should be stored.
path <- file.path(data_directory_combined_cleaned_files, "gene_expression_data_cleaned_sorted_genes_removed.csv")

# If the 'path' defined above does already point to a file, the execution of this code block is terminated and a message is 
# displayed informing that the file already exists.
if (file.exists(path)) {
    cat(paste("There is already a file present at the path: ", path))
} else {
    # Writing the data table to a CSV file.
    data.table::fwrite(gene_expression_data_genes_removed, path)
    cat(paste("The file has been created at the path: ", path))
}

The file has been created at the path:  C:/Users/laure/OneDrive/Documenten/Bachelor Thesis Data/combined_cleaned_data/gene_expression_data_cleaned_sorted_genes_removed.csv

<br></br>
<br></br>
__The file 'gene_expression_data_cleaned_log2_transformed_sorted.csv':__

To remove the 806 genes present in the array 'genes_to_delete' from the file 'gene_expression_data_cleaned_log2_transformed_sorted.csv', we first need to load the file from the directory 'data_directory_combined_cleaned_files'. This can be achieved by calling the function 'fread()' with as argument the path of the file that should be loaded into this notebook as a data table. To explicitly call the function 'fread()' from the 'data.table' package, the '::' operator is used.

In [27]:
# The path of the gene expression data file 'gene_expression_data_cleaned_log2_transformed_sorted.csv' to be loaded into this 
# notebook.
path <- file.path(data_directory_combined_cleaned_files, "gene_expression_data_cleaned_log2_transformed_sorted.csv")

# If the 'path' defined above does not point to a file, the execution of this code block is terminated and an error message
# is displayed.
if (!file.exists(path)) {
  stop("File not found: ", path)
}

# Loading the gene expression log2 transformed data as a data table into this notebook by calling the function 'fread()'.
gene_expression_data_log2_transformed <- data.table::fread(path)

cat("The gene_expression log2 transformed data:")
gene_expression_data_log2_transformed

The gene_expression log2 transformed data:

Gene ID            Gene Name    TCGA-06-0125-01A-01 TCGA-06-0125-02A-11
1     ENSG00000000003.15 TSPAN6       6.2813885           6.3909686          
2     ENSG00000000005.6  TNMD         0.4890291           0.5047729          
3     ENSG00000000419.13 DPM1         6.6211713           6.0101555          
4     ENSG00000000457.14 SCYL3        2.9151002           2.6988630          
5     ENSG00000000460.17 C1orf112     2.8042395           2.0485501          
6     ENSG00000000938.13 FGR          3.0116924           4.1234179          
7     ENSG00000000971.16 CFH          4.1643116           4.1232772          
8     ENSG00000001036.14 FUCA2        6.0163069           6.0871891          
9     ENSG00000001084.13 GCLC         3.9551919           4.5782444          
10    ENSG00000001167.14 NFYA         4.6598275           4.2626962          
11    ENSG00000001460.18 STPG1        0.9851361           1.2699308          
12    ENSG00000001461.17 NIPAL3       4.5680808           4.6379753          
13    ENSG00000001497.18 LAS1L        4.5091067           3.6295898          
14    ENSG00000001561.7  ENPP4        1.8009103           3.6469691          
15    ENSG00000001617.12 SEMA3F       4.2123514           3.4097847          
16    ENSG00000001626.16 CFTR         1.0656412           0.3409610          
17    ENSG00000001629.10 ANKIB1       6.2918245           6.4554472          
18    ENSG00000001630.17 CYP51A1      3.0380498           3.0805383          
19    ENSG00000001631.16 KRIT1        3.1875777           2.6249431          
20    ENSG00000002016.18 RAD52        4.8138581           3.1954578          
21    ENSG00000002330.14 BAD          4.9574968           4.9000939          
22    ENSG00000002549.12 LAP3         7.3599164           7.4047635          
23    ENSG00000002586.20 CD99         8.8049944           9.4524286          
24    ENSG00000002587.10 HS3ST1       4.7398427           3.7017376          
25    ENSG00000002745.13 WNT16        0.3229665           0.5985558          
26    ENSG00000002746.15 HECW1        0.8404431           1.1025909          
27    ENSG00000002834.18 LASP1        6.7902299           6.6897786          
28    ENSG00000002919.15 SNX11        4.5093475           4.5601891          
29    ENSG00000002933.9  TMEM176A     4.4595300           5.9446804          
30    ENSG00000003056.8  M6PR         6.1253577           6.2813088          
⋮     ⋮                  ⋮            ⋮                   ⋮                  
20408 ENSG00000288009.1  AL353135.2   1.82338253          1.5150564          
20409 ENSG00000288011.1  AC024597.1   0.10634832          0.3474389          
20410 ENSG00000288012.1  AP003307.1   0.89631060          1.7381625          
20411 ENSG00000288033.1  AC137894.4   2.10829026          0.5537537          
20412 ENSG00000288041.1  AC092819.3   0.04879418          0.0000000          
20413 ENSG00000288045.1  AL352979.4   1.69314123          1.6303589          
20414 ENSG00000288048.1  AC104088.3   2.82962634          2.1896348          
20415 ENSG00000288060.1  AL355338.1   2.23637016          1.5708029          
20416 ENSG00000288062.1  AL136981.3   2.34445926          1.0628816          
20417 ENSG00000288066.1  AC097448.1   4.47109639          4.2839366          
20418 ENSG00000288088.1  AL606923.2   1.56978271          2.5295711          
20419 ENSG00000288095.1  AC005618.4   0.57879383          0.5544415          
20420 ENSG00000288156.1  AC104530.1   1.71479501          2.3495917          
20421 ENSG00000288162.1  AL596442.4   0.12021921          0.1415636          
20422 ENSG00000288234.1  BX255925.4   0.79210571          0.0000000          
20423 ENSG00000288398.1  AL109627.1   3.88612088          4.2988416          
20424 ENSG00000288525.1  AC011228.3   0.17517327          0.0000000          
20425 ENSG00000288538.1  AP002985.1   2.73281187          0.8530375          
20426 ENSG00000288545.1  AC023421.2   0.93847400          1.2928406          
20427 ENSG00000288558.2  DUS

Now that the file has been loaded, we can alter the 'gene_expression_data_log2_transformed' data table to delete the rows that represent these genes. This can be achieved by indexing the 'gene_expression_data_log2_transformed' data table based on whether the genes appear within the 'genes_to_delete' array.

In [28]:
# Removing the genes present in the 'genes_to_delete' array from the 'gene_expression_data' data table by indexing the 
# 'gene_expression_data_log2_transformed' data table based on whether the genes appear within the 'genes_to_delete' array.
gene_expression_data_log2_transformed_genes_removed <- gene_expression_data_log2_transformed[!(sub("\\..*", "", gene_expression_data_log2_transformed$"Gene ID") %in% genes_to_delete),]

print("The gene expression log2 transformed data after the genes have been removed:")
gene_expression_data_log2_transformed_genes_removed

[1] "The gene expression log2 transformed data after the genes have been removed:"


Gene ID            Gene Name    TCGA-06-0125-01A-01 TCGA-06-0125-02A-11
1     ENSG00000000419.13 DPM1         6.6211713           6.0101555          
2     ENSG00000000457.14 SCYL3        2.9151002           2.6988630          
3     ENSG00000000460.17 C1orf112     2.8042395           2.0485501          
4     ENSG00000000938.13 FGR          3.0116924           4.1234179          
5     ENSG00000000971.16 CFH          4.1643116           4.1232772          
6     ENSG00000001036.14 FUCA2        6.0163069           6.0871891          
7     ENSG00000001084.13 GCLC         3.9551919           4.5782444          
8     ENSG00000001167.14 NFYA         4.6598275           4.2626962          
9     ENSG00000001460.18 STPG1        0.9851361           1.2699308          
10    ENSG00000001461.17 NIPAL3       4.5680808           4.6379753          
11    ENSG00000001561.7  ENPP4        1.8009103           3.6469691          
12    ENSG00000001617.12 SEMA3F       4.2123514           3.4097847          
13    ENSG00000001626.16 CFTR         1.0656412           0.3409610          
14    ENSG00000001629.10 ANKIB1       6.2918245           6.4554472          
15    ENSG00000001630.17 CYP51A1      3.0380498           3.0805383          
16    ENSG00000001631.16 KRIT1        3.1875777           2.6249431          
17    ENSG00000002016.18 RAD52        4.8138581           3.1954578          
18    ENSG00000002330.14 BAD          4.9574968           4.9000939          
19    ENSG00000002549.12 LAP3         7.3599164           7.4047635          
20    ENSG00000002587.10 HS3ST1       4.7398427           3.7017376          
21    ENSG00000002745.13 WNT16        0.3229665           0.5985558          
22    ENSG00000002746.15 HECW1        0.8404431           1.1025909          
23    ENSG00000002834.18 LASP1        6.7902299           6.6897786          
24    ENSG00000002919.15 SNX11        4.5093475           4.5601891          
25    ENSG00000002933.9  TMEM176A     4.4595300           5.9446804          
26    ENSG00000003056.8  M6PR         6.1253577           6.2813088          
27    ENSG00000003137.8  CYP26B1      1.5579737           2.8159238          
28    ENSG00000003147.19 ICA1         4.2903654           3.2008339          
29    ENSG00000003249.15 DBNDD1       6.1980639           5.7457940          
30    ENSG00000003393.15 ALS2         4.3310029           4.2947531          
⋮     ⋮                  ⋮            ⋮                   ⋮                  
19602 ENSG00000288002.1  AC091912.3   2.08103278          2.1943708          
19603 ENSG00000288009.1  AL353135.2   1.82338253          1.5150564          
19604 ENSG00000288011.1  AC024597.1   0.10634832          0.3474389          
19605 ENSG00000288012.1  AP003307.1   0.89631060          1.7381625          
19606 ENSG00000288033.1  AC137894.4   2.10829026          0.5537537          
19607 ENSG00000288041.1  AC092819.3   0.04879418          0.0000000          
19608 ENSG00000288045.1  AL352979.4   1.69314123          1.6303589          
19609 ENSG00000288048.1  AC104088.3   2.82962634          2.1896348          
19610 ENSG00000288060.1  AL355338.1   2.23637016          1.5708029          
19611 ENSG00000288062.1  AL136981.3   2.34445926          1.0628816          
19612 ENSG00000288066.1  AC097448.1   4.47109639          4.2839366          
19613 ENSG00000288088.1  AL606923.2   1.56978271          2.5295711          
19614 ENSG00000288095.1  AC005618.4   0.57879383          0.5544415          
19615 ENSG00000288156.1  AC104530.1   1.71479501          2.3495917          
19616 ENSG00000288162.1  AL596442.4   0.12021921          0.1415636          
19617 ENSG00000288234.1  BX255925.4   0.79210571          0.0000000          
19618 ENSG00000288398.1  AL109627.1   3.88612088          4.2988416          
19619 ENSG00000288525.1  AC011228.3   0.17517327          0.0000000          
19620 ENSG00000288538.1  AP002985.1   2.73281187          0.8530375          
19621 ENSG00000288545.1  AC0

Next, we can also replace the part of the gene IDs present in the 'gene_expression_data_log2_transformed_genes_removed' data table that contain a dot followed by any number of values with an empty string such that only the part of the gene IDs remain that actually encode the gene. This would allow us to later retrieve information about the genes present in the 'genes_location_data' data table, which will be defined later, directly by comparing the IDs of the gene rather than having to remove some part of one of the strings first.

In [29]:
# Replacing the part of the gene IDs present in the 'gene_expression_log2_transformed_data_genes_removed' data table that 
# contain a dot followed by any number of values with an empty string such that only the part of the gene IDs remain that 
# actually encode the gene.
gene_expression_data_log2_transformed_genes_removed$'Gene ID' <- gsub("\\.\\d+$", "", gene_expression_data_log2_transformed_genes_removed$'Gene ID')

print("The gene expression data after the gene IDs have been replaced:")
gene_expression_data_log2_transformed_genes_removed

[1] "The gene expression data after the gene IDs have been replaced:"


Gene ID         Gene Name    TCGA-06-0125-01A-01 TCGA-06-0125-02A-11
1     ENSG00000000419 DPM1         6.6211713           6.0101555          
2     ENSG00000000457 SCYL3        2.9151002           2.6988630          
3     ENSG00000000460 C1orf112     2.8042395           2.0485501          
4     ENSG00000000938 FGR          3.0116924           4.1234179          
5     ENSG00000000971 CFH          4.1643116           4.1232772          
6     ENSG00000001036 FUCA2        6.0163069           6.0871891          
7     ENSG00000001084 GCLC         3.9551919           4.5782444          
8     ENSG00000001167 NFYA         4.6598275           4.2626962          
9     ENSG00000001460 STPG1        0.9851361           1.2699308          
10    ENSG00000001461 NIPAL3       4.5680808           4.6379753          
11    ENSG00000001561 ENPP4        1.8009103           3.6469691          
12    ENSG00000001617 SEMA3F       4.2123514           3.4097847          
13    ENSG00000001626 CFTR         1.0656412           0.3409610          
14    ENSG00000001629 ANKIB1       6.2918245           6.4554472          
15    ENSG00000001630 CYP51A1      3.0380498           3.0805383          
16    ENSG00000001631 KRIT1        3.1875777           2.6249431          
17    ENSG00000002016 RAD52        4.8138581           3.1954578          
18    ENSG00000002330 BAD          4.9574968           4.9000939          
19    ENSG00000002549 LAP3         7.3599164           7.4047635          
20    ENSG00000002587 HS3ST1       4.7398427           3.7017376          
21    ENSG00000002745 WNT16        0.3229665           0.5985558          
22    ENSG00000002746 HECW1        0.8404431           1.1025909          
23    ENSG00000002834 LASP1        6.7902299           6.6897786          
24    ENSG00000002919 SNX11        4.5093475           4.5601891          
25    ENSG00000002933 TMEM176A     4.4595300           5.9446804          
26    ENSG00000003056 M6PR         6.1253577           6.2813088          
27    ENSG00000003137 CYP26B1      1.5579737           2.8159238          
28    ENSG00000003147 ICA1         4.2903654           3.2008339          
29    ENSG00000003249 DBNDD1       6.1980639           5.7457940          
30    ENSG00000003393 ALS2         4.3310029           4.2947531          
⋮     ⋮               ⋮            ⋮                   ⋮                  
19602 ENSG00000288002 AC091912.3   2.08103278          2.1943708          
19603 ENSG00000288009 AL353135.2   1.82338253          1.5150564          
19604 ENSG00000288011 AC024597.1   0.10634832          0.3474389          
19605 ENSG00000288012 AP003307.1   0.89631060          1.7381625          
19606 ENSG00000288033 AC137894.4   2.10829026          0.5537537          
19607 ENSG00000288041 AC092819.3   0.04879418          0.0000000          
19608 ENSG00000288045 AL352979.4   1.69314123          1.6303589          
19609 ENSG00000288048 AC104088.3   2.82962634          2.1896348          
19610 ENSG00000288060 AL355338.1   2.23637016          1.5708029          
19611 ENSG00000288062 AL136981.3   2.34445926          1.0628816          
19612 ENSG00000288066 AC097448.1   4.47109639          4.2839366          
19613 ENSG00000288088 AL606923.2   1.56978271          2.5295711          
19614 ENSG00000288095 AC005618.4   0.57879383          0.5544415          
19615 ENSG00000288156 AC104530.1   1.71479501          2.3495917          
19616 ENSG00000288162 AL596442.4   0.12021921          0.1415636          
19617 ENSG00000288234 BX255925.4   0.79210571          0.0000000          
19618 ENSG00000288398 AL109627.1   3.88612088          4.2988416          
19619 ENSG00000288525 AC011228.3   0.17517327          0.0000000          
19620 ENSG00000288538 AP002985.1   2.73281187          0.8530375          
19621 ENSG00000288545 AC023421.2   0.93847400          1.2928406          
19622 ENSG00000288558 DUS4L-BCAP29 3.34135959          2.8081997          
19623 ENSG00000288559 AC016394.

To be sure, we can check whether we have not created any duplicate genes by removing part of the gene IDs. This can be achieved by calling the function 'unique()' which returns the number of unique records and check whether this is equal to the number of records present in the 'gene_expression_data_log2_transformed_genes_removed' data table. 

In [30]:
# Checking whether all the gene IDs present in the 'Gene ID' column of the 'gene_expression_data_log2_transformed_genes_removed' 
# data table are unique.
unique_genes <- unique(gene_expression_data_log2_transformed_genes_removed$'Gene ID')

if (length(unique_genes) == nrow(gene_expression_data_log2_transformed_genes_removed)) {
  cat("All genes are unique.")
} else {
  cat("There are duplicated genes.")
}

All genes are unique.

In addition, we can also check whether any of the gene IDs present in the 'Gene ID' column of the 'gene_expression_data_log2_transformed_genes_removed' data table can not be mapped to a gene ID in the 'annotation_genes' data table.

In [31]:
# Checking whether any of the gene IDs present in the 'Gene ID' column of the 'gene_expression_data_log2_transformed_genes_removed' 
# data table can not be mapped to a gene ID in the 'annotation_genes' data table.
gene_ids_not_mapped <- !gene_expression_data_log2_transformed_genes_removed$'Gene ID' %in% annotation_genes$ensembl_gene_id

# Retrieving the gene IDs which can not be mapped to a gene ID which are present in the 'ensembl_gene_id' column of the 
# 'annotation_genes' data table.
gene_ids <- gene_expression_data_log2_transformed_genes_removed$'Gene ID'[gene_ids_not_mapped]

# Displaying the gene IDs that cannot be mapped to a gene ID in the annotation data.
if (length(gene_ids) == 0) {
    cat("All the gene IDs can be mapped to a gene ID in the annotation data.")
} else {
    cat("The following gene IDs cannot be mapped to a gene ID in the annotation data:\n")
    cat(gene_ids)
    cat("\n\nThe number of gene IDs that cannot be mapped to a gene ID in the annotation data:\n")
    cat(length(gene_ids))
}

All the gene IDs can be mapped to a gene ID in the annotation data.

As we can see from the output above, all of the gene IDs present in the 'Gene ID' column of the 'gene_expression_data_log2_transformed_genes_removed' data table can be mapped to a gene ID in the 'annotation_genes' data table.

Next, we can store the resulting data table 'gene_expression_data_log2_transformed_genes_removed' featuring this information. This can be achieved by calling the function 'fwrite()' from the 'data.table' library which takes as arguments the data table to be stored and the location where the data table should be stored.

In [32]:
# The path where the 'gene_expression_data_log2_transformed_genes_removed' data table should be stored.
path <- file.path(data_directory_combined_cleaned_files, "gene_expression_data_cleaned_log2_transformed_sorted_genes_removed.csv")

# If the 'path' defined above does already point to a file, the execution of this code block is terminated and a message is 
# displayed informing that the file already exists.
if (file.exists(path)) {
    cat(paste("There is already a file present at the path: ", path))
} else {
    # Writing the data table to a CSV file.
    data.table::fwrite(gene_expression_data_log2_transformed_genes_removed, path)
    cat(paste("The file has been created at the path: ", path))
}

The file has been created at the path:  C:/Users/laure/OneDrive/Documenten/Bachelor Thesis Data/combined_cleaned_data/gene_expression_data_cleaned_log2_transformed_sorted_genes_removed.csv

##### Discarding the 806 genes from the array of genes 'genes'

To remove the 806 genes present in the array 'genes_to_delete' from the array 'genes', we can call the function 'setdiff()' which returns all the elements in the "genes" array that are not present in the 'genes_to_delete' array. 

In [33]:
# Removing the genes present in the 'genes_to_delete' array from the 'genes' array.
genes <- setdiff(genes, genes_to_delete)

We can check whether indeed all the 806 genes present in the 'genes_to_delete' array have been removed from the array of genes called 'genes' by running the following code.

In [34]:
# Checking whether the 'genes' appear in the 'genes_to_delete' array.
missing_genes <- genes %in% genes_to_delete

# Retrieving the genes which are present in the 'genes_to_delete' array.
genes_missing = genes[missing_genes]

# Displaying the missing genes.
if (length(genes_missing) == 0) {
    cat("All the genes present in the 'genes_to_delete' array have been removed.")
} else {
    cat("The following genes present in the 'genes_to_delete' array have not been removed:\n")
    cat(genes_missing)
    cat("\n\nThe number of genes present in the 'genes_to_delete' array that have not been removed:\n")
    cat(length(genes_missing))
}

All the genes present in the 'genes_to_delete' array have been removed.

As we can see from the output above, indeed all the 806 genes have been removed from the array of genes called 'genes' which means that now for all of the genes the necessary information is stored within the annotation data 'annotation_genes' and we can continue with the next step. We can now use this annotation data to retrieve the locations of the genes. Before we do this, we should first create a data table to store the location information for each of the genes present in the array 'genes'. This can be achieved by calling the function 'data.table()' present in the data.table library. Within this function call, we can set the column 'gene' to contain the genes present in the array 'genes'.

In [35]:
# Creating a data table to store the location information for each of the genes present in the array 'genes' and adding all
# these genes to the column 'gene'.
genes_location_data <- data.table::data.table(gene = genes, chromosome = character(), start_position = numeric(), end_position = numeric(), strand = character())

cat("The 'genes_location_data' data table:")
genes_location_data

Warning message in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, :
"Item 2 has 0 rows but longest item has 19631; filled with NA"
Warning message in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, :
"Item 3 has 0 rows but longest item has 19631; filled with NA"
Warning message in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, :
"Item 4 has 0 rows but longest item has 19631; filled with NA"
Warning message in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, :
"Item 5 has 0 rows but longest item has 19631; filled with NA"


The 'genes_location_data' data table:

gene            chromosome start_position end_position strand
1     ENSG00000000419 NA         NA             NA           NA    
2     ENSG00000000457 NA         NA             NA           NA    
3     ENSG00000000460 NA         NA             NA           NA    
4     ENSG00000000938 NA         NA             NA           NA    
5     ENSG00000000971 NA         NA             NA           NA    
6     ENSG00000001036 NA         NA             NA           NA    
7     ENSG00000001084 NA         NA             NA           NA    
8     ENSG00000001167 NA         NA             NA           NA    
9     ENSG00000001460 NA         NA             NA           NA    
10    ENSG00000001461 NA         NA             NA           NA    
11    ENSG00000001561 NA         NA             NA           NA    
12    ENSG00000001617 NA         NA             NA           NA    
13    ENSG00000001626 NA         NA             NA           NA    
14    ENSG00000001629 NA         NA             NA           NA    
15    ENSG00000001630 NA         NA             NA           NA    
16    ENSG00000001631 NA         NA             NA           NA    
17    ENSG00000002016 NA         NA             NA           NA    
18    ENSG00000002330 NA         NA             NA           NA    
19    ENSG00000002549 NA         NA             NA           NA    
20    ENSG00000002587 NA         NA             NA           NA    
21    ENSG00000002745 NA         NA             NA           NA    
22    ENSG00000002746 NA         NA             NA           NA    
23    ENSG00000002834 NA         NA             NA           NA    
24    ENSG00000002919 NA         NA             NA           NA    
25    ENSG00000002933 NA         NA             NA           NA    
26    ENSG00000003056 NA         NA             NA           NA    
27    ENSG00000003137 NA         NA             NA           NA    
28    ENSG00000003147 NA         NA             NA           NA    
29    ENSG00000003249 NA         NA             NA           NA    
30    ENSG00000003393 NA         NA             NA           NA    
⋮     ⋮               ⋮          ⋮              ⋮            ⋮     
19602 ENSG00000288002 NA         NA             NA           NA    
19603 ENSG00000288009 NA         NA             NA           NA    
19604 ENSG00000288011 NA         NA             NA           NA    
19605 ENSG00000288012 NA         NA             NA           NA    
19606 ENSG00000288033 NA         NA             NA           NA    
19607 ENSG00000288041 NA         NA             NA           NA    
19608 ENSG00000288045 NA         NA             NA           NA    
19609 ENSG00000288048 NA         NA             NA           NA    
19610 ENSG00000288060 NA         NA             NA           NA    
19611 ENSG00000288062 NA         NA             NA           NA    
19612 ENSG00000288066 NA         NA             NA           NA    
19613 ENSG00000288088 NA         NA             NA           NA    
19614 ENSG00000288095 NA         NA             NA           NA    
19615 ENSG00000288156 NA         NA             NA           NA    
19616 ENSG00000288162 NA         NA             NA           NA    
19617 ENSG00000288234 NA         NA             NA           NA    
19618 ENSG00000288398 NA         NA             NA           NA    
19619 ENSG00000288525 NA         NA             NA           NA    
19620 ENSG00000288538 NA         NA             NA           NA    
19621 ENSG00000288545 NA         NA             NA           NA    
19622 ENSG00000288558 NA         NA             NA           NA    
19623 ENSG00000288559 NA         NA             NA           NA    
19624 ENSG00000288573 NA         NA             NA           NA    
19625 ENSG00000288586 NA         NA             NA           NA    
19626 ENSG00000288596 NA         NA             NA           NA    
19627 ENSG00000288612 NA         NA             NA           NA    
19628 ENSG00000288658 NA         NA             NA           N

To verify whether all the genes from the 'genes' character array have been added to the 'genes_location_data' data table, we can check whether the number of rows corresponds to the number of elements in the 'genes' character array.

In [36]:
# Checking whether all the genes from the 'genes' character array have been added to the 'genes_location_data' data table.
if (nrow(genes_location_data) == length(genes)) {
    cat("All of the genes from the 'genes' character array have been added.")
} else {
    cat("Not all of the genes from the 'genes' character array have been added.")
}

All of the genes from the 'genes' character array have been added.

Now, we can add the location data for each of the genes by retrieving the data from the 'annotation_genes' data table and insert it into the 'genes_location_data' data table.

Since we do not want to retrieve two records for a single gene, we need to check whether all the genes in the 'annotation_genes' data table are unique. This can be achieved by calling the function 'unique()' with as argument the column of the genes.

In [37]:
# Checking whether all the genes in the 'annotation_genes' data table are unique.
unique_genes_annotation <- unique(annotation_genes$ensembl_gene_id)

if (length(unique_genes_annotation) == nrow(annotation_genes)) {
  cat("All genes in the 'annotation_genes' data table are unique.")
} else {
  cat("There are non-unique genes in the 'annotation_genes' data table.")
}

All genes in the 'annotation_genes' data table are unique.

Now that we have verified that all genes in the 'annotation_genes' data table are unique, we can safely retrieve the records for a single gene. This can be achieved by first calling the function 'match()' which retrieves the matching rows based on the genes present in the 'gene' column from the 'genes_location_data' data table and the 'ensembl_gene_id' column from the 'annotation_genes' data table. From these matching rows, the chromosome, the starting position, the ending position, and the strand can be retrieved to fill in the missing values in the 'genes_location_data' data table. 

To be consistent with how the location data is represented for both the CpG sites and the genes, we transform the values 1 and -1 for the 'strand' column to the values '+' and '-' respectively and add the string 'chr' before the chromosome numbers.

In [38]:
# Matching the genes in the 'genes_location_data' data table to the 'annotation_genes' data table.
matching_rows <- match(genes_location_data$gene, annotation_genes$ensembl_gene_id)

# Filling in the missing values in the 'genes_location_data' data table with the chromosome, start position, end position, 
# and strand from the 'annotation_genes' data table.
genes_location_data$chromosome <- paste0("chr", annotation_genes$chromosome_name[matching_rows])
genes_location_data$start_position <- as.numeric(annotation_genes$start_position[matching_rows])
genes_location_data$end_position <- as.numeric(annotation_genes$end_position[matching_rows])
genes_location_data$strand <- ifelse(annotation_genes$strand[matching_rows] == 1, '+', '-')

To increase the readability of the data table and increase the structure we can sort the table based on the 'chromosome' column followed by the 'start_position' column. To define the order in which the chromosomes should be sorted, the function 'factor' can be used first. To actually order the data table, we can call the function 'order()'.

In [39]:
# Defining the order in which the chromosomes should be sorted by calling the function 'factor()'.
genes_location_data$chromosome <- factor(genes_location_data$chromosome, levels = c("chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX", "chrY"))

# Sorting the table based on the chromosome and the position to increase the structure by calling the function 'order()'.
genes_location_data_sorted = genes_location_data[order(genes_location_data$chromosome, start_position)]

cat("The resulting 'genes_location_data_sorted' data table:")
genes_location_data_sorted

The resulting 'genes_location_data_sorted' data table:

gene            chromosome start_position end_position strand
1     ENSG00000227232 chr1         14404          29570      -     
2     ENSG00000278267 chr1         17369          17436      -     
3     ENSG00000268903 chr1        135141         135895      -     
4     ENSG00000269981 chr1        137682         137965      -     
5     ENSG00000279457 chr1        185217         195411      -     
6     ENSG00000225972 chr1        629062         629433      +     
7     ENSG00000225630 chr1        629640         630683      +     
8     ENSG00000237973 chr1        631074         632616      +     
9     ENSG00000229344 chr1        632757         633438      +     
10    ENSG00000240409 chr1        633535         633741      +     
11    ENSG00000248527 chr1        633696         634376      +     
12    ENSG00000198744 chr1        634376         634922      +     
13    ENSG00000225880 chr1        824228         827539      -     
14    ENSG00000228794 chr1        825138         859446      +     
15    ENSG00000272438 chr1        904834         915976      +     
16    ENSG00000230699 chr1        911435         914948      +     
17    ENSG00000223764 chr1        916865         921016      -     
18    ENSG00000187634 chr1        923923         944575      +     
19    ENSG00000188976 chr1        944203         959309      -     
20    ENSG00000187961 chr1        960584         965719      +     
21    ENSG00000272512 chr1        995966         998051      -     
22    ENSG00000188290 chr1        998962        1000172      -     
23    ENSG00000187608 chr1       1001138        1014540      +     
24    ENSG00000224969 chr1       1011997        1013193      -     
25    ENSG00000188157 chr1       1020120        1056118      +     
26    ENSG00000217801 chr1       1063079        1069355      +     
27    ENSG00000131591 chr1       1081818        1116361      -     
28    ENSG00000207730 chr1       1167104        1167198      +     
29    ENSG00000207607 chr1       1167863        1167952      +     
30    ENSG00000198976 chr1       1169005        1169087      +     
⋮     ⋮               ⋮          ⋮              ⋮            ⋮     
19602 ENSG00000184164 chr22      49918167       49927540     +     
19603 ENSG00000278869 chr22      49933197       49935277     -     
19604 ENSG00000198355 chr22      49960768       49964072     +     
19605 ENSG00000100427 chr22      50059391       50085426     -     
19606 ENSG00000073150 chr22      50170731       50180295     +     
19607 ENSG00000170638 chr22      50185913       50199598     +     
19608 ENSG00000273188 chr22      50191724       50192402     -     
19609 ENSG00000273253 chr22      50199090       50200837     -     
19610 ENSG00000073169 chr22      50201011       50217616     +     
19611 ENSG00000272836 chr22      50205585       50206062     -     
19612 ENSG00000273137 chr22      50208461       50209542     -     
19613 ENSG00000128159 chr22      50217689       50245023     -     
19614 ENSG00000188130 chr22      50245450       50261716     -     
19615 ENSG00000185386 chr22      50263713       50270767     -     
19616 ENSG00000196576 chr22      50274979       50307646     -     
19617 ENSG00000205593 chr22      50309030       50327012     -     
19618 ENSG00000100239 chr22      50343304       50445090     +     
19619 ENSG00000100241 chr22      50443219       50483923     -     
19620 ENSG00000128165 chr22      50481543       50486440     +     
19621 ENSG00000100258 chr22      50502949       50507702     -     
19622 ENSG00000025770 chr22      50508224       50524780     +     
19623 ENSG00000025708 chr22      50525752       50530032     -     
19624 ENSG00000177989 chr22      50529710       50532506     -     
19625 ENSG00000217442 chr22      50551112       50562919     -     
19626 ENSG00000205559 chr22      50583026       50595634     +     
19627 ENSG00000008735 chr22      50600793       50613981     +     
19628 ENSG00000100299 chr22      50622754       50628173     -

## Storing the Resulting Genes Location Data

Now the location data of the genes has been retrieved, we can store the resulting data table 'genes_location_data_sorted' featuring this information. This can be achieved by calling the function 'fwrite()' from the 'data.table' library which takes as arguments the data table to be stored and the location where the data table should be stored.

In [40]:
# The path where the 'genes_location_data_sorted' data table should be stored.
path <- file.path(data_directory_location_files, "genes_location_data.csv")

# If the 'path' defined above does already point to a file, the execution of this code block is terminated and a message is 
# displayed informing that the file already exists.
if (file.exists(path)) {
    cat(paste("There is already a file present at the path: ", path))
} else {
    # Writing the data table to a CSV file.
    data.table::fwrite(genes_location_data_sorted, path)
    cat(paste("The file has been created at the path: ", path))
}

There is already a file present at the path:  C:/Users/laure/OneDrive/Documenten/Bachelor Thesis Data/location_data/genes_location_data.csv